name: lint - clj

on: workflow_dispatch

jobs:
  self-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint .
          github_token: ${{ secrets.GITHUB_TOKEN }}
